package model

import (
	"errors"
	"path/filepath"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"
)

// File is an uploaded blob attached to a clipboard room (blob may live on disk).
type File struct {
	ID          string
	Name        string
	ContentType string
	Data        []byte // optional; may be empty when only metadata / streaming
	Size        int64  // authoritative size when Data is not loaded
	TTL         time.Duration
	ExpiresAt   time.Time
	UploadedAt  time.Time
}

// FileInfo is the public metadata returned by list/upload APIs.
type FileInfo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Size        int64  `json:"size"`
	ContentType string `json:"contentType"`
	UploadedAt  string `json:"uploadedAt"`
	ExpiresAt   string `json:"expiresAt"`
}

// FileListResponse is returned by GET .../files.
type FileListResponse struct {
	Key               string     `json:"key"`
	Files             []FileInfo `json:"files"`
	FileUploadEnabled bool       `json:"fileUploadEnabled"`
}

// RoomSettings is per-clipboard room configuration for file features.
type RoomSettings struct {
	Key               string `json:"key"`
	FileUploadEnabled bool   `json:"fileUploadEnabled"`
}

// RoomSettingsUpdate is the body for PUT .../settings.
type RoomSettingsUpdate struct {
	FileUploadEnabled *bool  `json:"fileUploadEnabled"`
	AdminPassword     string `json:"adminPassword,omitempty"`
	Password          string `json:"password,omitempty"` // alias for adminPassword
}

var (
	fileIDPattern   = regexp.MustCompile(`^[a-f0-9]{8,32}$`)
	ErrInvalidFile  = errors.New("invalid file name")
	ErrEmptyFile    = errors.New("file is empty")
	ErrFileTooLarge = errors.New("file exceeds size limit")
)

// ValidateFileID accepts hex ids generated by the server.
func ValidateFileID(id string) (string, error) {
	id = strings.TrimSpace(id)
	if !fileIDPattern.MatchString(id) {
		return "", errors.New("invalid file id")
	}
	return id, nil
}

// SanitizeFileName strips path components and control characters.
func SanitizeFileName(name string) (string, error) {
	name = strings.TrimSpace(name)
	name = filepath.Base(name)
	name = strings.ReplaceAll(name, "\\", "")
	name = strings.ReplaceAll(name, "/", "")
	// Reject invalid UTF-8 before rune processing (ranging would otherwise
	// silently replace bad bytes with U+FFFD and mask the input problem).
	if !utf8.ValidString(name) {
		return "", ErrInvalidFile
	}
	// Drop control characters.
	var b strings.Builder
	for _, r := range name {
		if r < 32 || r == 127 {
			continue
		}
		b.WriteRune(r)
	}
	name = strings.TrimSpace(b.String())
	if name == "" || name == "." || name == ".." {
		return "", ErrInvalidFile
	}
	// Cap display name length (bytes), always rune-safe: byte slicing here
	// would split multi-byte characters and produce invalid UTF-8.
	if len(name) > 200 {
		runes := []rune(name)
		if len(runes) > 120 {
			runes = runes[:120]
		}
		for len(runes) > 0 && len(string(runes)) > 200 {
			runes = runes[:len(runes)-1]
		}
		name = string(runes)
	}
	return name, nil
}

// FileInfoFrom converts a stored file to API metadata.
func FileInfoFrom(f File) FileInfo {
	size := f.Size
	if size <= 0 && len(f.Data) > 0 {
		size = int64(len(f.Data))
	}
	return FileInfo{
		ID:          f.ID,
		Name:        f.Name,
		Size:        size,
		ContentType: f.ContentType,
		UploadedAt:  f.UploadedAt.UTC().Format(time.RFC3339),
		ExpiresAt:   f.ExpiresAt.UTC().Format(time.RFC3339),
	}
}
